---
abstract: 'Get many Plugins of Padre at once'
author:
  - 'Gabor Szabo'
build_requires:
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.790'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: Task-Padre-Plugins
no_index:
  directory:
    - inc
    - t
requires:
  Padre::Plugin::AcmePlayCode: 0.08
  Padre::Plugin::Alarm: 0.02
  Padre::Plugin::CSS: 0.05
  Padre::Plugin::CommandLine: 0.04
  Padre::Plugin::Encode: 0.1.3
  Padre::Plugin::Encrypt: 0.05
  Padre::Plugin::HTML: 0.08
  Padre::Plugin::HTMLExport: 0.04
  Padre::Plugin::InstallPARDist: 0.01
  Padre::Plugin::JavaScript: 0.25
  Padre::Plugin::PAR: 0.04
  Padre::Plugin::PerlCritic: 0.06
  Padre::Plugin::PerlTidy: 0.05
  Padre::Plugin::Pip: 0.13
  Padre::Plugin::SVK: 0.01
  Padre::Plugin::Vi: 0.21
  Padre::Plugin::ViewInBrowser: 0.06
  Padre::Plugin::XML: 0.05
resources:
  license: http://dev.perl.org/licenses/
version: 0.14
